// Re-export all garden components
export { GardenView } from './GardenView'
export { GardenStats } from './GardenStats'
export { ElementDetails } from './ElementDetails'
export { ShelfView } from './ShelfView'
export { ShelfElement } from './ShelfElement'
export { FriendGardenView } from './FriendGardenView'
export { GardenRoomManager } from './GardenRoomManager'
export { IsometricRoomView } from './IsometricRoomView'
export { GardenCompanion } from './companion'
// Upgrade system components
export { ElementUpgradeButton } from './ElementUpgradeButton'
export { UpgradeConfirmModal } from './UpgradeConfirmModal'
export { UpgradeResultModal } from './UpgradeResultModal'
export { ElementUpgradeManager } from './ElementUpgradeManager'
export { UpgradeAnimation } from './UpgradeAnimation'
