import type { GardenerLevel } from '@/types'

/**
 * 🎯 Система уровней (50 уровней)
 *
 * Формула опыта скорректирована для достижения 30 уровня за ~6 месяцев активной игры
 *
 * Прогрессия:
 * - Уровни 1-10: Быстрая (1-2 недели)
 * - Уровни 11-20: Средняя (1-3 месяца)
 * - Уровни 21-30: Долгая (3-6 месяцев)
 * - Уровни 31-50: Очень долгая (6+ месяцев)
 *
 * Целевое время:
 * - Уровень 10: ~2 недели
 * - Уровень 20: ~3 месяца
 * - Уровень 30: ~6-8 месяцев ✅
 * - Уровень 50: ~1.5-2 года
 */

/**
 * Формула расчёта требуемого опыта для уровня
 */
export function calculateExperienceForLevel(level: number): number {
  if (level === 1) return 0

  // Уровни 2-10: быстрая прогрессия (1-2 недели)
  if (level <= 10) {
    return Math.floor(100 * Math.pow(level - 1, 1.4))
  }

  // Уровни 11-20: средняя (1-3 месяца)
  if (level <= 20) {
    const base = 6300
    return base + (level - 10) * 2000
  }

  // Уровни 21-30: долгая (3-6 месяцев)
  if (level <= 30) {
    const base = 46300
    return base + (level - 20) * 10000
  }

  // Уровни 31-40: очень долгая
  if (level <= 40) {
    const base = 146300
    return base + (level - 30) * 20000
  }

  // Уровни 41-50: экстремально долгая
  const base = 346300
  return base + (level - 40) * 30000
}

/**
 * Максимальное накопление заморозок стрика по уровню
 */
export function getMaxStreakFreezes(level: number): number {
  if (level < 7) return 3
  if (level < 13) return 5
  if (level < 20) return 7
  if (level < 31) return 10
  return 15 // Уровни 31-50
}

/**
 * Количество бесплатных перестановок в день по уровню
 */
export function getFreeRearrangesPerDay(level: number): number {
  if (level < 3) return 0
  if (level < 8) return 1
  if (level < 11) return 2
  if (level < 14) return 3
  if (level < 16) return 4
  if (level >= 16) return Infinity // Безлимитные с 16 уровня
  return 0
}

/**
 * 🎯 50 УРОВНЕЙ САДОВНИКА
 * Каждый уровень тщательно сбалансирован для долгосрочной прогрессии
 */
export const GARDENER_LEVELS: readonly GardenerLevel[] = [
  // ===== УРОВНИ 1-10: НОВИЧОК (1-2 недели) =====
  {
    level: 1,
    name: 'Росток',
    emoji: '🌱',
    minExperience: 0,
    maxExperience: 99,
    sproutReward: 50,
    gemReward: 0,
    rooms: 1,
    totalSlots: 16,
    rarityBonus: 0,
    experienceBonus: 0,
    maxStreakFreezes: 3,
    benefits: [
      'Все социальные функции',
      'Базовая статистика',
      'Доступ к магазину',
    ],
  },
  {
    level: 2,
    name: 'Побег',
    emoji: '🌿',
    minExperience: 100,
    maxExperience: 249,
    sproutReward: 100,
    gemReward: 0,
    rooms: 2,
    totalSlots: 32,
    rarityBonus: 2,
    experienceBonus: 5,
    maxStreakFreezes: 3,
    benefits: ['+1 комната (32 слота)', '+2% редких растений', '+5% опыта'],
  },
  {
    level: 3,
    name: 'Бутон',
    emoji: '🌼',
    minExperience: 250,
    maxExperience: 520,
    sproutReward: 150,
    gemReward: 1,
    rooms: 3,
    totalSlots: 48,
    rarityBonus: 3,
    experienceBonus: 8,
    maxStreakFreezes: 3,
    freeRearrangesPerDay: 1,
    benefits: ['+1 комната', '+1 бесплатная перестановка/день', '+8% опыта'],
  },
  {
    level: 4,
    name: 'Цветок',
    emoji: '🌸',
    minExperience: 521,
    maxExperience: 913,
    sproutReward: 200,
    gemReward: 0,
    rooms: 4,
    totalSlots: 64,
    rarityBonus: 5,
    experienceBonus: 10,
    maxStreakFreezes: 3,
    freeRearrangesPerDay: 1,
    benefits: ['+1 комната', '+5% редких растений', '+10% опыта'],
  },
  {
    level: 5,
    name: 'Садовник',
    emoji: '🌻',
    minExperience: 914,
    maxExperience: 1452,
    sproutReward: 300,
    gemReward: 3,
    rooms: 5,
    totalSlots: 80,
    rarityBonus: 6,
    experienceBonus: 12,
    maxStreakFreezes: 3,
    freeRearrangesPerDay: 1,
    specialUnlock: 'Магазин тем оформления',
    benefits: ['+1 комната', 'Магазин тем оформления', '+12% опыта'],
  },
  {
    level: 6,
    name: 'Ботаник',
    emoji: '🍀',
    minExperience: 1453,
    maxExperience: 2163,
    sproutReward: 400,
    gemReward: 2,
    rooms: 6,
    totalSlots: 96,
    rarityBonus: 8,
    experienceBonus: 15,
    maxStreakFreezes: 3,
    freeRearrangesPerDay: 1,
    specialUnlock: 'Еженедельная статистика',
    benefits: ['+1 комната', 'Графики настроения за неделю', '+15% опыта'],
  },
  {
    level: 7,
    name: 'Знаток',
    emoji: '🌺',
    minExperience: 2164,
    maxExperience: 3085,
    sproutReward: 500,
    gemReward: 3,
    streakFreezeReward: 1,
    rooms: 7,
    totalSlots: 112,
    rarityBonus: 10,
    experienceBonus: 18,
    maxStreakFreezes: 5,
    freeRearrangesPerDay: 1,
    specialUnlock: 'Заморозка стрика (1/неделя)',
    benefits: [
      '+1 комната',
      '+1 заморозка стрика/неделю',
      '+10% редких',
      '+18% опыта',
    ],
  },
  {
    level: 8,
    name: 'Флорист',
    emoji: '🌹',
    minExperience: 3086,
    maxExperience: 4248,
    sproutReward: 600,
    gemReward: 2,
    rooms: 8,
    totalSlots: 128,
    rarityBonus: 12,
    experienceBonus: 20,
    maxStreakFreezes: 5,
    freeRearrangesPerDay: 2,
    benefits: ['+1 комната', '+2 бесплатные перестановки/день', '+20% опыта'],
  },
  {
    level: 9,
    name: 'Эксперт',
    emoji: '🌳',
    minExperience: 4249,
    maxExperience: 5681,
    sproutReward: 700,
    gemReward: 4,
    rooms: 9,
    totalSlots: 144,
    rarityBonus: 14,
    experienceBonus: 22,
    maxStreakFreezes: 5,
    freeRearrangesPerDay: 2,
    specialUnlock: 'Создавать приватные челленджи',
    benefits: [
      '+1 комната',
      'Приватные челленджи',
      '+14% редких',
      '+22% опыта',
    ],
  },
  {
    level: 10,
    name: 'Мастер',
    emoji: '🎋',
    minExperience: 5682,
    maxExperience: 8299,
    sproutReward: 1000,
    gemReward: 5,
    autoFreezeReward: 1,
    rooms: 10,
    totalSlots: 160,
    rarityBonus: 16,
    experienceBonus: 25,
    maxStreakFreezes: 5,
    freeRearrangesPerDay: 2,
    specialUnlock: 'Расширенная статистика + Авто-заморозка',
    benefits: [
      '+1 комната',
      'Месячная статистика',
      '+1 авто-заморозка (разовая)',
      '+16% редких',
      '+25% опыта',
    ],
  },

  // ===== УРОВНИ 11-20: ПРОДВИНУТЫЙ (1-3 месяца) =====
  {
    level: 11,
    name: 'Виртуоз',
    emoji: '🪴',
    minExperience: 8300,
    maxExperience: 10299,
    sproutReward: 1200,
    gemReward: 3,
    rooms: 11,
    totalSlots: 176,
    rarityBonus: 18,
    experienceBonus: 28,
    maxStreakFreezes: 5,
    freeRearrangesPerDay: 3,
    benefits: ['+1 комната', '+3 бесплатные перестановки/день', '+28% опыта'],
  },
  {
    level: 12,
    name: 'Куратор',
    emoji: '🌴',
    minExperience: 10300,
    maxExperience: 12299,
    sproutReward: 1400,
    gemReward: 4,
    rooms: 12,
    totalSlots: 192,
    rarityBonus: 20,
    experienceBonus: 30,
    maxStreakFreezes: 5,
    freeRearrangesPerDay: 3,
    specialUnlock: 'Экспорт статистики как изображение',
    benefits: [
      '+1 комната',
      'Экспорт статистики для шеринга',
      '+20% редких',
      '+30% опыта',
    ],
  },
  {
    level: 13,
    name: 'Хранитель',
    emoji: '🌲',
    minExperience: 12300,
    maxExperience: 14299,
    sproutReward: 1600,
    gemReward: 5,
    streakFreezeReward: 2,
    rooms: 13,
    totalSlots: 208,
    rarityBonus: 22,
    experienceBonus: 32,
    maxStreakFreezes: 7,
    freeRearrangesPerDay: 3,
    benefits: [
      '+1 комната',
      '+2 заморозки стрика/неделю',
      '+22% редких',
      '+32% опыта',
    ],
  },
  {
    level: 14,
    name: 'Архитектор',
    emoji: '🏛️',
    minExperience: 14300,
    maxExperience: 16299,
    sproutReward: 1800,
    gemReward: 4,
    rooms: 14,
    totalSlots: 224,
    rarityBonus: 24,
    experienceBonus: 35,
    maxStreakFreezes: 7,
    freeRearrangesPerDay: 4,
    benefits: ['+1 комната', '+4 бесплатные перестановки/день', '+24% редких'],
  },
  {
    level: 15,
    name: 'Легенда',
    emoji: '⭐',
    minExperience: 16300,
    maxExperience: 18299,
    sproutReward: 2500,
    gemReward: 10,
    rooms: 15,
    totalSlots: 240,
    rarityBonus: 26,
    experienceBonus: 38,
    maxStreakFreezes: 7,
    freeRearrangesPerDay: 4,
    specialUnlock: 'Значок "Легенда" в профиле',
    benefits: [
      '+1 комната',
      'Значок "Легенда" в профиле',
      '+26% редких',
      '+38% опыта',
    ],
  },
  {
    level: 16,
    name: 'Титан',
    emoji: '🗿',
    minExperience: 18300,
    maxExperience: 20299,
    sproutReward: 3000,
    gemReward: 6,
    rooms: 16,
    totalSlots: 256,
    rarityBonus: 28,
    experienceBonus: 40,
    maxStreakFreezes: 7,
    freeRearrangesPerDay: Infinity,
    specialUnlock: 'Безлимитные перестановки',
    benefits: [
      '+1 комната',
      'Безлимитные перестановки',
      '+28% редких',
      '+40% опыта',
    ],
  },
  {
    level: 17,
    name: 'Феникс',
    emoji: '🔥',
    minExperience: 20300,
    maxExperience: 22299,
    sproutReward: 3500,
    gemReward: 8,
    rooms: 17,
    totalSlots: 272,
    rarityBonus: 30,
    experienceBonus: 42,
    maxStreakFreezes: 7,
    freeRearrangesPerDay: Infinity,
    specialUnlock: 'Восстановление дня (1 раз/месяц)',
    benefits: [
      '+1 комната',
      'Восстановить 1 пропущенный день/месяц',
      '+30% редких',
    ],
  },
  {
    level: 18,
    name: 'Оракул',
    emoji: '🔮',
    minExperience: 22300,
    maxExperience: 24299,
    sproutReward: 4000,
    gemReward: 10,
    rooms: 18,
    totalSlots: 288,
    rarityBonus: 32,
    experienceBonus: 45,
    maxStreakFreezes: 7,
    freeRearrangesPerDay: Infinity,
    specialUnlock: 'Подсказка элемента на завтра',
    benefits: [
      '+1 комната',
      'Видишь завтрашний элемент',
      '+32% редких',
      '+45% опыта',
    ],
  },
  {
    level: 19,
    name: 'Мистик',
    emoji: '✨',
    minExperience: 24300,
    maxExperience: 26299,
    sproutReward: 4500,
    gemReward: 8,
    rooms: 19,
    totalSlots: 304,
    rarityBonus: 34,
    experienceBonus: 48,
    maxStreakFreezes: 7,
    freeRearrangesPerDay: Infinity,
    benefits: ['+1 комната', '+10% ростков при посещении сада', '+34% редких'],
  },
  {
    level: 20,
    name: 'Божество',
    emoji: '👑',
    minExperience: 26300,
    maxExperience: 46299,
    sproutReward: 5000,
    gemReward: 20,
    autoFreezeReward: 1,
    rooms: 20,
    totalSlots: 320,
    rarityBonus: 36,
    experienceBonus: 50,
    maxStreakFreezes: 10,
    freeRearrangesPerDay: Infinity,
    specialUnlock: 'Тема "Божественный сад" + Авто-заморозка',
    benefits: [
      '+1 комната',
      'Тема "Божественный сад"',
      '+1 авто-заморозка (разовая)',
      '+36% редких',
      '+50% опыта',
    ],
  },

  // ===== УРОВНИ 21-30: ЭКСПЕРТ (3-6 месяцев) =====
  {
    level: 21,
    name: 'Космос',
    emoji: '🌌',
    minExperience: 46300,
    maxExperience: 56299,
    sproutReward: 6000,
    gemReward: 12,
    rooms: 22,
    totalSlots: 352,
    rarityBonus: 38,
    experienceBonus: 52,
    maxStreakFreezes: 10,
    freeRearrangesPerDay: Infinity,
    specialUnlock: 'Тема "Космос"',
    benefits: ['+2 комнаты', 'Тема "Космос"', '+38% редких', '+52% опыта'],
  },
  {
    level: 22,
    name: 'Вечность',
    emoji: '♾️',
    minExperience: 56300,
    maxExperience: 66299,
    sproutReward: 7000,
    gemReward: 14,
    streakFreezeReward: 3,
    rooms: 24,
    totalSlots: 384,
    rarityBonus: 40,
    experienceBonus: 55,
    maxStreakFreezes: 10,
    freeRearrangesPerDay: Infinity,
    benefits: [
      '+2 комнаты',
      '+3 заморозки стрика/неделю',
      '+40% редких',
      '+55% опыта',
    ],
  },
  {
    level: 23,
    name: 'Абсолют',
    emoji: '💫',
    minExperience: 66300,
    maxExperience: 76299,
    sproutReward: 8000,
    gemReward: 16,
    rooms: 26,
    totalSlots: 416,
    rarityBonus: 42,
    experienceBonus: 58,
    maxStreakFreezes: 10,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+42% редких', '+58% опыта'],
  },
  {
    level: 24,
    name: 'Трансцендент',
    emoji: '🌠',
    minExperience: 76300,
    maxExperience: 86299,
    sproutReward: 9000,
    gemReward: 18,
    rooms: 28,
    totalSlots: 448,
    rarityBonus: 44,
    experienceBonus: 60,
    maxStreakFreezes: 10,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+44% редких', '+60% опыта'],
  },
  {
    level: 25,
    name: 'Архонт',
    emoji: '🌟',
    minExperience: 86300,
    maxExperience: 96299,
    sproutReward: 10000,
    gemReward: 20,
    rooms: 30,
    totalSlots: 480,
    rarityBonus: 46,
    experienceBonus: 65,
    maxStreakFreezes: 10,
    freeRearrangesPerDay: Infinity,
    specialUnlock: 'Эксклюзивный титул "Архонт"',
    benefits: ['+2 комнаты', 'Титул "Архонт"', '+46% редких', '+65% опыта'],
  },
  {
    level: 26,
    name: 'Небожитель',
    emoji: '☁️',
    minExperience: 96300,
    maxExperience: 106299,
    sproutReward: 11000,
    gemReward: 22,
    rooms: 32,
    totalSlots: 512,
    rarityBonus: 48,
    experienceBonus: 70,
    maxStreakFreezes: 10,
    freeRearrangesPerDay: Infinity,
    specialUnlock: 'Тема "Небесные сады"',
    benefits: [
      '+2 комнаты',
      'Тема "Небесные сады"',
      '+48% редких',
      '+70% опыта',
    ],
  },
  {
    level: 27,
    name: 'Астральный',
    emoji: '🪐',
    minExperience: 106300,
    maxExperience: 116299,
    sproutReward: 12000,
    gemReward: 24,
    rooms: 34,
    totalSlots: 544,
    rarityBonus: 50,
    experienceBonus: 75,
    maxStreakFreezes: 10,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+50% редких', '+75% опыта'],
  },
  {
    level: 28,
    name: 'Бесконечность',
    emoji: '🌀',
    minExperience: 116300,
    maxExperience: 126299,
    sproutReward: 13000,
    gemReward: 26,
    rooms: 36,
    totalSlots: 576,
    rarityBonus: 52,
    experienceBonus: 80,
    maxStreakFreezes: 10,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+52% редких', '+80% опыта'],
  },
  {
    level: 29,
    name: 'Всевидящий',
    emoji: '👁️',
    minExperience: 126300,
    maxExperience: 136299,
    sproutReward: 14000,
    gemReward: 28,
    rooms: 38,
    totalSlots: 608,
    rarityBonus: 55,
    experienceBonus: 85,
    maxStreakFreezes: 10,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+55% редких', '+85% опыта'],
  },
  {
    level: 30,
    name: 'Творец',
    emoji: '🌈',
    minExperience: 136300,
    maxExperience: 146299,
    sproutReward: 15000,
    gemReward: 50,
    autoFreezeReward: 1,
    rooms: 40,
    totalSlots: 640,
    rarityBonus: 60,
    experienceBonus: 100,
    maxStreakFreezes: 10,
    freeRearrangesPerDay: Infinity,
    specialUnlock: 'Статус "Творец" - Высшее достижение',
    benefits: [
      '+2 комнаты',
      'Статус "Творец"',
      '+1 авто-заморозка',
      '+60% редких',
      '+100% опыта',
      'x2 награды за всё',
    ],
  },

  // ===== УРОВНИ 31-50: ХАРДКОР (6+ месяцев - 2 года) =====
  {
    level: 31,
    name: 'Первопроходец',
    emoji: '🚀',
    minExperience: 146300,
    maxExperience: 166299,
    sproutReward: 16000,
    gemReward: 30,
    rooms: 42,
    totalSlots: 672,
    rarityBonus: 62,
    experienceBonus: 105,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+62% редких', '+105% опыта'],
  },
  {
    level: 32,
    name: 'Пионер',
    emoji: '🎖️',
    minExperience: 166300,
    maxExperience: 186299,
    sproutReward: 17000,
    gemReward: 32,
    rooms: 44,
    totalSlots: 704,
    rarityBonus: 64,
    experienceBonus: 110,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+64% редких', '+110% опыта'],
  },
  {
    level: 33,
    name: 'Хранитель Света',
    emoji: '💡',
    minExperience: 186300,
    maxExperience: 206299,
    sproutReward: 18000,
    gemReward: 34,
    rooms: 46,
    totalSlots: 736,
    rarityBonus: 66,
    experienceBonus: 115,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+66% редких', '+115% опыта'],
  },
  {
    level: 34,
    name: 'Властелин Времени',
    emoji: '⏳',
    minExperience: 206300,
    maxExperience: 226299,
    sproutReward: 19000,
    gemReward: 36,
    rooms: 48,
    totalSlots: 768,
    rarityBonus: 68,
    experienceBonus: 120,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+68% редких', '+120% опыта'],
  },
  {
    level: 35,
    name: 'Искатель Истины',
    emoji: '🔍',
    minExperience: 226300,
    maxExperience: 246299,
    sproutReward: 20000,
    gemReward: 38,
    rooms: 50,
    totalSlots: 800,
    rarityBonus: 70,
    experienceBonus: 125,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    specialUnlock: 'Престиж-система',
    benefits: ['+2 комнаты', 'Доступ к престижу', '+70% редких', '+125% опыта'],
  },
  {
    level: 36,
    name: 'Мастер Реальности',
    emoji: '🎭',
    minExperience: 246300,
    maxExperience: 266299,
    sproutReward: 21000,
    gemReward: 40,
    rooms: 52,
    totalSlots: 832,
    rarityBonus: 72,
    experienceBonus: 130,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+72% редких', '+130% опыта'],
  },
  {
    level: 37,
    name: 'Космический Страж',
    emoji: '🛡️',
    minExperience: 266300,
    maxExperience: 286299,
    sproutReward: 22000,
    gemReward: 42,
    rooms: 54,
    totalSlots: 864,
    rarityBonus: 74,
    experienceBonus: 135,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+74% редких', '+135% опыта'],
  },
  {
    level: 38,
    name: 'Повелитель Судьбы',
    emoji: '🎲',
    minExperience: 286300,
    maxExperience: 306299,
    sproutReward: 23000,
    gemReward: 44,
    rooms: 56,
    totalSlots: 896,
    rarityBonus: 76,
    experienceBonus: 140,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+76% редких', '+140% опыта'],
  },
  {
    level: 39,
    name: 'Воплощение Гармонии',
    emoji: '☯️',
    minExperience: 306300,
    maxExperience: 326299,
    sproutReward: 24000,
    gemReward: 46,
    rooms: 58,
    totalSlots: 928,
    rarityBonus: 78,
    experienceBonus: 145,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+78% редких', '+145% опыта'],
  },
  {
    level: 40,
    name: 'Источник Силы',
    emoji: '⚡',
    minExperience: 326300,
    maxExperience: 346299,
    sproutReward: 25000,
    gemReward: 48,
    autoFreezeReward: 1,
    rooms: 60,
    totalSlots: 960,
    rarityBonus: 80,
    experienceBonus: 150,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    specialUnlock: 'Авто-заморозка + Титул "Источник"',
    benefits: [
      '+2 комнаты',
      'Титул "Источник Силы"',
      '+1 авто-заморозка',
      '+80% редких',
      '+150% опыта',
    ],
  },
  {
    level: 41,
    name: 'Небесный Император',
    emoji: '🏯',
    minExperience: 346300,
    maxExperience: 376299,
    sproutReward: 27000,
    gemReward: 50,
    rooms: 62,
    totalSlots: 992,
    rarityBonus: 82,
    experienceBonus: 155,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+82% редких', '+155% опыта'],
  },
  {
    level: 42,
    name: 'Божественный Кузнец',
    emoji: '⚒️',
    minExperience: 376300,
    maxExperience: 406299,
    sproutReward: 29000,
    gemReward: 52,
    rooms: 64,
    totalSlots: 1024,
    rarityBonus: 84,
    experienceBonus: 160,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+84% редких', '+160% опыта'],
  },
  {
    level: 43,
    name: 'Вершина Мудрости',
    emoji: '📿',
    minExperience: 406300,
    maxExperience: 436299,
    sproutReward: 31000,
    gemReward: 54,
    rooms: 66,
    totalSlots: 1056,
    rarityBonus: 86,
    experienceBonus: 165,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+86% редких', '+165% опыта'],
  },
  {
    level: 44,
    name: 'Сияние Вечности',
    emoji: '✴️',
    minExperience: 436300,
    maxExperience: 466299,
    sproutReward: 33000,
    gemReward: 56,
    rooms: 68,
    totalSlots: 1088,
    rarityBonus: 88,
    experienceBonus: 170,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+88% редких', '+170% опыта'],
  },
  {
    level: 45,
    name: 'Воплощение Совершенства',
    emoji: '💠',
    minExperience: 466300,
    maxExperience: 496299,
    sproutReward: 35000,
    gemReward: 58,
    rooms: 70,
    totalSlots: 1120,
    rarityBonus: 90,
    experienceBonus: 175,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+90% редких', '+175% опыта'],
  },
  {
    level: 46,
    name: 'Хозяин Вселенной',
    emoji: '🌐',
    minExperience: 496300,
    maxExperience: 526299,
    sproutReward: 37000,
    gemReward: 60,
    rooms: 72,
    totalSlots: 1152,
    rarityBonus: 92,
    experienceBonus: 180,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+92% редких', '+180% опыта'],
  },
  {
    level: 47,
    name: 'Властелин Миров',
    emoji: '🪐',
    minExperience: 526300,
    maxExperience: 556299,
    sproutReward: 39000,
    gemReward: 62,
    rooms: 74,
    totalSlots: 1184,
    rarityBonus: 94,
    experienceBonus: 185,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+94% редких', '+185% опыта'],
  },
  {
    level: 48,
    name: 'Великий Архитектор',
    emoji: '📐',
    minExperience: 556300,
    maxExperience: 586299,
    sproutReward: 41000,
    gemReward: 64,
    rooms: 76,
    totalSlots: 1216,
    rarityBonus: 96,
    experienceBonus: 190,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+96% редких', '+190% опыта'],
  },
  {
    level: 49,
    name: 'Абсолютное Бытие',
    emoji: '🔆',
    minExperience: 586300,
    maxExperience: 616299,
    sproutReward: 43000,
    gemReward: 66,
    rooms: 78,
    totalSlots: 1248,
    rarityBonus: 98,
    experienceBonus: 195,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    benefits: ['+2 комнаты', '+98% редких', '+195% опыта'],
  },
  {
    level: 50,
    name: 'ОМНИПОТЕНТ',
    emoji: '👁️‍🗨️',
    minExperience: 616300,
    maxExperience: Infinity,
    sproutReward: 100000,
    gemReward: 500,
    autoFreezeReward: 5,
    rooms: 999,
    totalSlots: 15984,
    rarityBonus: 100,
    experienceBonus: 200,
    maxStreakFreezes: 15,
    freeRearrangesPerDay: Infinity,
    specialUnlock: 'ОМНИПОТЕНТ - Высшее божественное звание',
    benefits: [
      'Безлимитные комнаты',
      '+100% редких растений',
      '+200% опыт',
      'x3 награды за всё',
      'Все премиум фичи навсегда',
      'Титул "ОМНИПОТЕНТ"',
      '+5 авто-заморозок (разовая)',
      'Эксклюзивная аура',
      'Доступ ко всем будущим фичам',
    ],
  },
] as const
